### ISSUE TITLE
there is no "findDels_no5bpPadding.py"!!!

### ISSUE THREAD

**Issue by panpandzf** [bejerano-lab/percomorphCONDELs#1]
First of all thank you so much for analyzing the script, it's great.
I saw that the script "findDels_no5bpPadding.py" will be used in the script of "getChainDelsMinusPaddedAssemblyGaps.sh", but this script does not exist in the script directory. Should this script be "findDels.py"? Or will the script be shared after the article is accepted for publication.
Looking forward to your reply.

**Comment by panpandzf** [comment]
prepRefGenesWrapper.sh 
line 12: sort -k1,1 -k2,2n scriptsDir+"/../processedInputs/filterBEDs/ASM223467v1_ensembl98_canonicalTSS_withInfo.tab" > /tmp/tempSortFile
line 13 : mv /tmp/tempSortFile scriptsDir+"/../processedInputs/filterBEDs/ASM223467v1_ensembl98_canonicalTSS_withInfo.tab"

It seems wrong, and an error is reported when running: 
"sort: cannot read: scriptsDir+/../processedInputs/filterBEDs/ASM223467v1_ensembl98_canonicalTSS_withInfo.tab: No such file or directory"

**Comment by chenhijy** [comment]
thanks for alerting me to these issues! i've made some edits. let me know if you still have trouble.

**Comment by panpandzf** [comment]
Thank you very much for your reply! we very much hope to use your edited scripts for our related projects. If I find a problem, I will report it to you immediately.

**Comment by panpandzf** [comment]
Hello, sorry to bother you at this moment, is there an alternative to doblastzchinanet.pl? 
For example, Make Lastz Chains (https://github.com/hillerlab/make_lastz_chains).
We log in directly to the computing nodes to deliver tasks. I don’t know how to solve the problem of parasol? Any help will be greatly appreciated
best

**Comment by chenhijy** [comment]
You could definitely try the Hiller Lab pipeline. I'm not sure if the output would be identical.

The source code for doBlastzChainNet.pl is available online and could be adapted to run via a different parallelization mechanism.

Here are some relevant links in case you haven't seen them:
http://genomewiki.ucsc.edu/index.php/Parasol_job_control_system
http://genomewiki.ucsc.edu/index.php/DoBlastzChainNet.pl
https://groups.google.com/a/soe.ucsc.edu/g/genome/search?q=parasol
https://github.com/ucscGenomeBrowser/kent/blob/1310a50e728de886096a9c7127d13dcadf3e404a/src/hg/utils/automation/doBlastzChainNet.pl#L4
